version: "3.9"
services:
  todo-web:
    image: diamol/ch06-todo-list
    restart: unless-stopped
    ports:
      - "80:80"
    environment:
      - Database:Provider=Postgres
    depends_on:
      - tododb
    networks:
      - app-net
    secrets:
      - source: postgres-connection
        target: /app/secrets.json

  todo-db:
    image: diamol/postgres:11.5
    ports:
      - "5433:5432"
    networks:
      - app-net

networks:
  app-net:

secrets:
  postgres-connection:
    file: ./secrets.json